# Required metadata
sonar.projectKey=com.lmig.forge.test.buildfarm:nodejs-010-project
sonar.projectName=LibertyForge :: Build Farm Test Projects :: Node.js 0.10 Test App
sonar.projectVersion=1.0
  
# Comma-separated paths to directories with sources (required)
sonar.sources=app
  
# Language
sonar.language=js
  
# Encoding of sources files
sonar.sourceEncoding=UTF-8