# Required metadata
sonar.projectKey=com.lmig.ci.distribution.cct:cicct-softphone-admin-ui
sonar.projectName=cicct-softphone-admin-ui
sonar.projectVersion=1.0
#Same as Jest config
sonar.sources=src/
sonar.exclusions=**/*.test.js,**/__test__/**/*,src/assets/**/*
sonar.typescript.lcov.reportPaths=coverage/lcov.info
