import { isNumberValid } from "utils";

//Not all worker attribute fields would logically be bulk updated. 
//Future stories will bulk update routing and default skills in addition to inactive fields to bulk disable users
export const availableAttributes: any = {
  ZERO_OUT_ENABLED: {
    label: "zeroOutEnabled",
    value: "zeroOutEnabled",
    type: "boolean",
    location: null
  },
  SELF_SERVICE_INDICATOR: {
    label: "selfServiceInd",
    value: "selfServiceInd",
    type: "boolean",
    location: null
  },
  PROFILE: {
    label: "profile_id",
    value: "profile_id",
    type: "number",
    validator: (value: any) => !isNaN(value as any),
    location: "attributes" // Add tooltip that it will also update agentAttribute1
  },
  DID: {
    label: "did",
    value: "did",
    type: "phone number",
    validator: (value: any) => isNumberValid(value.toString(), false),
    location: "attributes"// add tooltip that this is alone will not update someone's direct dial number, bulk update direct didal is not supported, this field also represents outgoing number for non DID users
  },
  ROUTING_TEAM: {
    label: "team",
    value: "team",
    type: "string",
    location: ["attributes","routing"]
  },
  ROUTING_SALES_ASSOC_WORKERS: {
    label: "sales_assoc_workers",
    value: "sales_assoc_workers",
    type: "string",
    location: ["attributes","routing"]
  }
};

export const jokes: string[] = [
  "What do you call a sleeping bull? A bulldozer.",
  "I ordered a chicken and an egg from Amazon. I’ll let you know.",
  "I decided to sell the vacuum cleaner — it was just gathering dust!",
  "What kind of jewelry do rabbits wear? 14 carrot gold.",
  "What do you call a girl in the middle of a tennis court? Annette.",
  "What kind of magic do cows believe in? Moodoo!",
  "Where do fish keep their money? In a river bank.",
  "Why do peppers make such good archers? Because they habanero.",
  "Struggling to think of what to buy someone for Christmas? Get theme a fridge and watch their face light up when they open it.",
  "It's easy to convince ladies not to eat Tide Pods but harder to deter gents.",
  "How do you get an astronaut’s baby to stop crying? You rocket.",
  "What did the llama say to his date? “Want to go on a picnic? Alpaca lunch.”",
  "What's a sea monster's favorite lunch? Fish and ships.",
  "I had a joke about canned juice but I couldn't concentrate.",
  "Where do books hide when they’re afraid? Under their covers.",
  "Why do cows have bells? Because their horns don’t work.",
  "I wouldn't buy anything with velcro. It's a total rip-off.",
  "I have an inferiority complex but it’s not a very good one.",
  "“I saw a 1000-year-old oil stain; it was from ancient Greece.”",
  "What do you call a Frenchman wearing sandals? Philippe Flop.",
  "What happened to the lost beef shipment? Nobody's herd.",
  "My wife asked why I didn’t buy her flowers. To be fair I didn’t know she sold flowers.",
  "Am I the only man my wife has ever dated? Unfortunately yes she said the others were all nines or tens!",
  "I was going to go on an expensive vacation with a classical pianist but he was too baroque.",
  "What do you call a fibbing cat? A lion.",
  "Why did the scarecrow win an award? It was outstanding in its field.",
  "What do you call a bundle of hay in a church? Christian Bale.",
  "Atheism is a non-prophet organization.",
  "I was going to go on an expensive vacation with a classical pianist but he was too baroque.",
  "I’m so good at sleeping I can do it with my eyes closed!",
  "What’s the difference between an African elephant and an Indian elephant? About 5000 miles.",
  "What do you call a sheep that knows karate? A lamb chop.",
  "The secret service isn't allowed to yell \"Get down!\" anymore when the president is about to be attacked. Now they have to yell \"Donald Duck!\"",
  "I heard there is a new shop called Moderation. They have everything in there.",
  "Why'd the fisherman order the halibut? Just for the halibut!",
  "Why was the belt sent to jail? For holding up a pair of pants!",
  "How did the pirate get his ship for so cheap? It was on sail.",
  "What did the police officer say to her belly button? You're under a vest!",
  "Have you heard about the new corduroy pillows — they're making headlines!",
  "What do you call a bear with no teeth? A gummy bear.",
  "“Siri” I asked my phone “why am I so bad with women?\" She responded “I’m Bixby you moron.”",
  "Why did the baseball player get arrested? He stole third base.",
  "“What’s your name son?” The principal asked his student. The kid replied “D-d-d-dav-dav-david sir.” “Do you have a stutter?” the principal asked. The student answered “No sir my dad has a stutter but the guy who registered my name was a real jerk.”",
  "I decided to sell the vacuum cleaner — it was just gathering dust!",
  "What’s an astronaut’s favorite part of a computer? The space bar.",
  "Can a kangaroo jump higher than a house? Of course houses can't jump.",
  "My daughter just shrieked at me “Daaaaaad you haven’t listened to a word I’ve said have you?” What an odd way to begin a conversation.",
  "What do you call a fly with a sore throat? A hoarse fly.",
  "People in Athens rarely get up before sunrise. Dawn is tough on Greece.",
  "Did you know that the first french fries weren’t cooked in France? They were cooked in Greece.",
  "What rock group has four men who don't sing? Mount Rushmore.",
  "What's a foot long and slippery? A slipper.",
  "I just found out Albert Einstein existed. My whole life I thought he was a theoretical physicist.A comma. A literalist takes everything literally. A kleptomaniac takes everything literally.",
  "Did you hear about the truck transporting steaks that got into a wreck? Some car T-Boned it.",
  "I used to hate facial hair but then it grew on me.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "Have you heard about those new corduroy pillows? They're making headlines.",
  "This morning Siri said “Don’t call me Shirley.” I accidentally left my phone in Airplane mode.",
  "What did the blanket say to the bed? I’ve got you covered.",
  "What do you call a cow with no legs? Ground beef.",
  "Imagine if you walked into a bar and there was a long line of people waiting to take a swing at you. That’s the punch line.",
  "Why did the orange stop halfway across the road? It ran out of juice.",
  "I hate Velcro. It's a rip off.",
  "How do you make holy water? You boil the hell out of it.",
  "What happens when frogs park illegally? They get toad.",
  "Why can't your hand be 12 inches long? Because then it would be a foot.",
  "What do computers eat for a snack? Microchips.",
  "“Singing in the shower is fun until you get soap in your mouth. Then it’s a soap opera.”",
  "Every time I take my dog to the park the ducks try to bite him. That’s what I get for buying a pure bread dog.",
  "Last night my wife and I watched two DVDs back to back. Luckily I was the one facing the TV.",
  "The shovel was a ground-breaking invention.",
  "They say that breakfast is the most important meal of the day. Well not if it’s poisoned. Then the antidote becomes the most important.",
  "What did one elevator say to the other elevator? I think I’m coming down with something.",
  "“Siri” I asked my phone “why am I so bad with women?\" She responded “I’m Bixby you moron.”",
  "I used to run a dating service for chickens but I was struggling to make hens meet.",
  "“Siri” I asked my phone “why am I so bad with women?\" She responded “I’m Bixby you moron.”",
  "I asked my dog what’s two minus two. He said nothing.",
  "What happened to the lost beef shipment? Nobody's herd.",
  "What did the drummer call his twin daughters? Anna one Anna two!",
  "Why did the poodle buy a clock? It wanted to be a watch dog.",
  "I ordered a chicken and an egg online. I'll let you know.",
  "I used to hate facial hair but then it grew on me.",
  "Yogurt is the most high class dairy product to buy. It’s so cultured.",
  "Can a kangaroo jump higher than a house? Of course houses can't jump.",
  "I used to be able to play piano by ear but now I have to use my hands.",
  "Why did the football coach go to the bank? To get his quarter back.",
  "Why didn't the skeleton cross the road? Because he had no guts!",
  "Yogurt is the most high class dairy product to buy. It’s so cultured.",
  "What do you call recently-married spiders? Newly-webs.",
  "Today I’m attaching a light to the ceiling but I’m afraid I’ll probably screw it up.",
  "I decided to sell the vacuum cleaner — it was just gathering dust!",
  "Did the hear about the ice cream truck accident? It crashed on a rocky road.",
  "How did the pirate get his ship for so cheap? It was on sail.",
  "I got my best friend a fridge for his birthday. I can’t wait to see his face light up when he opens it!",
  "To the person who stole my diary and then died: My thoughts are with your family.",
  "Our vacuum cleaner is getting old. It's just gathering dust.",
  "What do you call a snake that loves building houses? A boa constructor.",
  "Yogurt is the most high class dairy product to buy. It’s so cultured.",
  "What do you call a beehive without an exit? Unbelievable.",
  "What happens when a snowman throws a tantrum? He has a meltdown.",
  "What do you call a man wearing a rug on his head? Matt.",
  "Two sheep walk into a—baaaa.",
  "Do you know how many people are dead at a cemetery? All of them.",
  "A century ago two brothers decided it was possible to fly. And as you can see they were Wright.",
  "Did you hear Bruce Springsteen changed the lyrics to one of his songs? What’s he going to change next—his hair? His clothes? His face?",
  "My friend said that if he went off a cliff it would be on his own accord. It’s a good thing he drives a Civic.",
  "What do you call a factory that makes OK products? A satisfactory.",
  "To whoever stole my copy of Microsoft Office I will find you. You have my Word!",
  "I asked the IT guy \"How do you make a Motherboard?\" He said \"I tell her about my job.\"",
  "What did one leaf say to the other? I’m falling for you.",
  "Did you hear the story about the haunted lift? It really raised my spirits!",
  "My landlord told me we need to talk about the heating bill. \"Sure\" I said. \"My door is always open.\"",
  "What do you call two monkeys who share an Amazon account? Prime mates.",
  "How does a lawyer say goodbye? I'll be suing ya!",
  "I went to a seafood disco last week! Pulled a mussel!",
  "How do trees get on the internet? They log in.",
  "My friend keeps saying \"cheer up man it could be worse you could be stuck underground in a hole full of water.\" I know he means well.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels (bay gulls).",
  "What do you call a beehive without an exit? Un-bee-lievable.",
  "What did the plumber say to the singer? Nice pipes.",
  "Why did the deer go to the dentist? It had buck teeth.",
  "What does a nosey pepper do? It gets jalapeno business!",
  "My dad died because he couldn’t remember his blood type. He kept insisting we “be positive” but it’s just so hard without him.",
  "“Whoever stole my depression medication — I hope you’re happy now.”",
  "I have a joke about drilling but it’s boring.",
  "I ate a clock the other day. It was very time consuming.",
  "At the job interview they asked me “Where do you see yourself in five years?”",
  "How many telemarketers does it take to change a light bulb? Only one but he has to do it during dinner.",
  "I don't get why bakers aren't wealthier. They make so much dough.",
  "My dentist pulled out the wrong tooth. He said it was acci-dental.",
  "I went to buy a pair of camouflage pants but I couldn’t find any.",
  "Why couldn't the bicycle stand up by itself? It was two tired.",
  "What’s Forrest Gump’s password? 1forrest1.",
  "Where do crayons go on vacation? Color-ado.",
  "How do cows stay up to date? They read the Moo-spaper.",
  "We’re renovating the house and the first floor is going great but the second floor is another story.",
  "I wasn't going to get a brain transplant. But then I changed my mind.",
  "I’ve never gone to a gun range before. I decided to give it a shot!",
  "What do cows like to read? Cattle-logs.",
  "I hate Velcro. It's a rip off.",
  "How do you spell “candy” with just two letters? C and Y.",
  "The difference between a numerator and a denominator is a short line. Only a fraction of people will understand this",
  "If April showers bring May flowers what do May flowers bring? Pilgrims.",
  "An apple a day keeps the doctor away. At least it does if you throw it hard enough.",
  "Where do elephants store luggage? In a trunk.",
  "What happened to the dating slices of bread that disappeared overnight? Turns out they e-loafed! I hope they grow mold together.",
  "What do you get if you cross an angry sheep with a moody cow? An animal that’s in a baaaaad mooood.",
  "What's the difference between a man's wallet before and after kids? There are pictures where the money used to be.",
  "What do lazy farmers grow? Couch potatoes!",
  "Yogurt is the most high class dairy product to buy. It’s so cultured.",
  "Who were the greenest Presidents in US history? The bushes.",
  "What do you call a pig that does karate? A pork chop!",
  "After dinner my wife asked if I could clear the table. I needed a running start but I made it.",
  "I was in a job interview the other day and they asked if I could perform under pressure. I said no but I could perform Bohemian Rhapsody.",
  "I finally watched that documentary on clocks. It was about time.",
  "Struggling to think of what to buy someone for Christmas? Get theme a fridge and watch their face light up when they open it.",
  "What genre are national anthems? Country.",
  "Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan!",
  "Justice is a dish best served cold. If it were served warm it would be justwater.",
  "Did you hear about the kidnapping at school? He woke up.",
  "Did you hear about the king that went to the dentist? He needed to get crowns.",
  "I have a great joke about nepotism. But I’ll only tell it to my kids.",
  "What has five toes but isn't your foot? My foot.",
  "If you see a crime at an Apple store are you an iWitness?",
  "What did the calculator say to the pencil? You can count on me.",
  "Two cannibals are eating a clown. One says to the other 'Does this taste funny to you?",
  "Last night I had a dream I was a muffler. I woke up exhausted.",
  "I asked my dog what’s two minus two. He said nothing.",
  "Did you hear about the claustrophobic astronaut? He just wanted a bit more space.",
  "You know people say they pick their noses… but I feel like I was just born with mine!",
  "A sandwich walks into a bar. The barman says: 'sorry we don't serve food here'",
  "What’s worse than biting into an apple and finding a worm? Biting into an apple and finding half a worm.",
  "I have a joke about statistics but it’s not significant.",
  "I hate Velcro. It's a rip off.",
  "Ghosts are bad liars because you can see right through them.",
  "My friend was showing me his tool shed and pointed to a ladder. “That's my stepladder” he said. \"I never knew my real ladder.”",
  "My boss told me to have a good day so I went home!",
  "Where do books hide when they’re afraid? Under their covers.",
  "Why was the math book sad? It had too many problems.",
  "A father tells his son that he was adopted. “I want to meet my biological parents” the son demands. “We are your biological parents” the father responds. “Now pack up the new ones will pick you up in twenty minutes.”",
  "What happened to the lost beef shipment? Nobody's herd.",
  "I have a clean conscious—it's never been used.",
  "Did you hear the story about the haunted lift? It really raised my spirits!",
  "My wife gave me an ultimatum: Her or my addiction to sweets. The decision was a piece of cake.",
  "Where do elephants store luggage? In a trunk.",
  "Why were the utensils stuck together? They were spooning.",
  "To the person who stole my case of energy drinks: I bet you can't sleep at night.",
  "I asked the IT guy \"How do you make a Motherboard?\" He said \"I tell her about my job.\"",
  "How much money does a skunk have? Just one scent.",
  "Why was the big cat disqualified from the race? Because it was a cheetah!",
  "If I ever find the doctor who screwed up my limb replacement surgery…I’ll kill him with my bear hands.",
  "Did you know the first French fries weren’t really cooked in France? They were cooked in Grease! (Greece)",
  "In America using the metric system can get you in legal trouble.",
  "What brand of underwear do scientists wear? Kelvin Klein.",
  "Two cannibals are eating a clown. One says to the other 'Does this taste funny to you?",
  "I can tolerate algebra maybe even a little calculus but geometry is where I draw the line.",
  "My kid is blaming me for ruining their birthday. That's ridiculous I didn't even know it was today!",
  "What does a nosey pepper do? It gets jalapeno business!",
  "Did you hear about the cartoonist found dead at his home? Details are sketchy.",
  "What kind of bird works on a construction site? A crane.",
  "I want to name my puppies Rolex and Timex so I can have watch dogs.",
  "Held a poker night where the buy in was a prime ribeye. I invited my brother but he said the steaks were too high.",
  "A guy walked into a bar and lost the limbo contest.",
  "Justice is a dish best served cold. If it were served warm it would be justwater.",
  "I have a joke about hunting for fossils but you probably wouldn’t dig it.",
  "You know people say they pick their noses… but I feel like I was just born with mine!",
  "Mom texted me from the grocery store to say they’re out of pasta and we’re penneless.",
  "What time do ducks wake up? At the quack of dawn.",
  "Why'd the alternate universe Spider-Man do so well on his driving test? He's an excellent parallel Parker.",
  "I asked my date to meet me at the gym but she never showed up. I guess the two of us aren't going to work out.",
  "What has five toes but isn't your foot? My foot.",
  "I have a joke about kites but it would just sail over your head.",
  "I told my wife that a husband is like a fine wine: we just get better with age. The next day she locked me in the cellar.",
  "I just don't trust stairs they're always up to something.",
  "Did you hear about the 12-inch dog? It was a foot long.",
  "During quarantine no one got my humor. I guess it was all the inside jokes.",
  "RIP boiling water. You will be mist.",
  "What sound does a witches car make? Broom Broom",
  "What's E.T. short for? Because he's only got little legs!",
  "What happened when the blue ship and the red ship collided at sea? Their crews were marooned.",
  "What did the 0 say to the 8? Nice belt!",
  "One of my friends and I just get together to eat hot dogs and tell the honest truth. It’s a frank relationship.",
  "What’s a scarecrow’s favorite fruit? Straw-berries",
  "I hated facial hair but then it grew on me.",
  "Why was the broom late? It over-swept.",
  "Why couldn’t the toilet paper cross the road? It got stuck in a crack.",
  "6:30 is hands down the best time on the clock.",
  "In the beef army there was a soldier who always snuck up on the enemy from the left or right. He was a flank steak.",
  "I gave away all my used batteries today. Free of charge!",
  "In 2017 I didn't do a marathon. I didn't do one in 2018 2019 or 2020 either. This is a running joke.",
  "What do you call a factory that makes okay products. A satisfactory.",
  "What’s more unbelievable than a talking dog? A spelling bee.",
  "How many tickles does it take to make an octopus laugh? Ten tickles.",
  "What’s that Nevada city where all the dentists visit? Floss Vegas.",
  "An invisible man married and invisible women. The kids were nothing to look at.",
  "Struggling to think of what to buy someone for Christmas? Get theme a fridge and watch their face light up when they open it.",
  "What time did the man go to the dentist? Tooth hurt-y!",
  "My therapist told me I have problems expressing my emotions. Can’t say I’m surprised.",
  "Am I the only man my wife has ever dated? Unfortunately yes she said the others were all nines or tens!",
  "My dad died because he couldn’t remember his blood type. He kept insisting we “be positive” but it’s just so hard without him.",
  "The difference between a numerator and a denominator is a short line. Only a fraction of people will understand this",
  "Who were the greenest Presidents in US history? The bushes.",
  "Why do seagulls fly over the sea? If they flew over the bay they would be bagels.",
  "Did you hear about the outlet who got in a fight with the power cord? He thought he could socket to him.",
  "Where do armies belong? In your sleeves.",
  "What do dogs and phones have in common? Both have collar ID.",
  "Does anybody know where a guy can find a person to hang out with talk to and enjoy spending time with? I'm just asking for a friend.",
  "The coach went to the bank to get his quarterback.",
  "Lance isn't that common a name these days but in medieval times they were called lance-a-lot.",
  "Why did the boy bring a ladder on the bus? He wanted to go to high school.",
  "What's E.T. short for? Because he's only got little legs!",
  "Why did the tomato blush? It saw the salad dressing.",
  "Where do elephants store luggage? In a trunk.",
  "Why did the man fall down the well? Because he couldn't see that well!",
  "Did you heard about the giant that threw up? It's all over town!",
  "What brand of underwear do scientists wear? Kelvin Klein.",
  "Why do bananas wear sunscreen? Because they peel.",
  "Two guys walked into a bar. The third guy ducked.",
  "What did the sink tell the toilet? You look flushed!",
  "What did the cannibal choose as his last meal? Five Guys.",
  "What’s the best air to breathe if you want to be rich? Millionaire.",
  "What time do ducks wake up? At the quack of dawn.",
  "What did the buffalo say to its son when he left? Bison!",
  "What's Forrest Gump's computer password? 1forrest1",
  "Two sheep walk into a—baaaa."
];